/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LabirintoRouteImport } from './routes/labirinto'
import { Route as LoginRouteImport } from './routes/login'
import { Route as PaisRouteImport } from './routes/pais'
import { Route as PlayRouteImport } from './routes/play'
import { Route as TreinoRouteImport } from './routes/treino'
import { Route as VestiarioRouteImport } from './routes/vestiario'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LabirintoRoute = LabirintoRouteImport.update({
  id: '/labirinto',
  path: '/labirinto',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const PaisRoute = PaisRouteImport.update({
  id: '/pais',
  path: '/pais',
  getParentRoute: () => rootRouteImport,
} as any)
const PlayRoute = PlayRouteImport.update({
  id: '/play',
  path: '/play',
  getParentRoute: () => rootRouteImport,
} as any)
const TreinoRoute = TreinoRouteImport.update({
  id: '/treino',
  path: '/treino',
  getParentRoute: () => rootRouteImport,
} as any)
const VestiarioRoute = VestiarioRouteImport.update({
  id: '/vestiario',
  path: '/vestiario',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/labirinto': typeof LabirintoRoute
  '/login': typeof LoginRoute
  '/pais': typeof PaisRoute
  '/play': typeof PlayRoute
  '/treino': typeof TreinoRoute
  '/vestiario': typeof VestiarioRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/labirinto': typeof LabirintoRoute
  '/login': typeof LoginRoute
  '/pais': typeof PaisRoute
  '/play': typeof PlayRoute
  '/treino': typeof TreinoRoute
  '/vestiario': typeof VestiarioRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/labirinto': typeof LabirintoRoute
  '/login': typeof LoginRoute
  '/pais': typeof PaisRoute
  '/play': typeof PlayRoute
  '/treino': typeof TreinoRoute
  '/vestiario': typeof VestiarioRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/labirinto'
    | '/login'
    | '/pais'
    | '/play'
    | '/treino'
    | '/vestiario'
    | '/api/auth/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/labirinto'
    | '/login'
    | '/pais'
    | '/play'
    | '/treino'
    | '/vestiario'
    | '/api/auth/$'
  id:
    | '__root__'
    | '/'
    | '/labirinto'
    | '/login'
    | '/pais'
    | '/play'
    | '/treino'
    | '/vestiario'
    | '/api/auth/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LabirintoRoute: typeof LabirintoRoute
  LoginRoute: typeof LoginRoute
  PaisRoute: typeof PaisRoute
  PlayRoute: typeof PlayRoute
  TreinoRoute: typeof TreinoRoute
  VestiarioRoute: typeof VestiarioRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/labirinto': {
      id: '/labirinto'
      path: '/labirinto'
      fullPath: '/labirinto'
      preLoaderRoute: typeof LabirintoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pais': {
      id: '/pais'
      path: '/pais'
      fullPath: '/pais'
      preLoaderRoute: typeof PaisRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/play': {
      id: '/play'
      path: '/play'
      fullPath: '/play'
      preLoaderRoute: typeof PlayRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/treino': {
      id: '/treino'
      path: '/treino'
      fullPath: '/treino'
      preLoaderRoute: typeof TreinoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vestiario': {
      id: '/vestiario'
      path: '/vestiario'
      fullPath: '/vestiario'
      preLoaderRoute: typeof VestiarioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LabirintoRoute: LabirintoRoute,
  LoginRoute: LoginRoute,
  PaisRoute: PaisRoute,
  PlayRoute: PlayRoute,
  TreinoRoute: TreinoRoute,
  VestiarioRoute: VestiarioRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
